In [1]:
import sys
import os
from pathlib import Path
import pandas as pd

In [2]:
# Set the path to the project root directory
# and add the src directory to the Python path
project_root = os.path.abspath("..")
src_path = os.path.join(project_root, "src")
if src_path not in sys.path:
    sys.path.append(src_path)

from utils import load_excel_files

In [3]:
# Definir rutas
raw_path = "C:/Allianz/prueba_allianz/data/raw"
output_path = "C:/Allianz/prueba_allianz/data/processed"
parquet_file = os.path.join(output_path, "allianz_consolidado.parquet")
csv_file = os.path.join(output_path, "allianz_consolidado.csv")

In [4]:
# Consolidar archivos excel en un solo dataframe
df_all = load_excel_files(raw_path)
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2087581 entries, 0 to 2087580
Data columns (total 32 columns):
 #   Column                     Dtype
---  ------                     -----
 0   fecha_registro             object
 1   comparison_id              object
 2   fecha_nacimiento           object
 3   edad                       object
 4   ocupacion                  object
 5   tipo_identificacion        object
 6   genero                     object
 7   fasecolda_id               object
 8   marca                      object
 9   clase                      object
 10  referencia_vehiculo        object
 11  vehiculo_uso               object
 12  tipo_caja                  object
 13  valor_fasecolda            object
 14  modelo                     object
 15  dane_id                    object
 16  ciudad                     object
 17  departamento_id            object
 18  departamento               object
 19  vehiculo_nuevo             object
 20  aseguradora_producto       object
 21  competencia                object
 22  cotizacion_fecha           object
 23  valor_prima                object
 24  tipo_cobertura             object
 25  rce                        object
 26  perdida_total_cobertura    object
 27  perdida_parcial_deducible  object
 28  rce_limite_unico           object
 29  emitido_producto           object
 30  emitido_cotizacion         object
 31  source_file                object
dtypes: object(32)
memory usage: 509.7+ MB

In [5]:
df_all.head()

,fecha_registro,comparison_id,fecha_nacimiento,edad,ocupacion,tipo_identificacion,genero,fasecolda_id,marca,clase,...,cotizacion_fecha,valor_prima,tipo_cobertura,rce,perdida_total_cobertura,perdida_parcial_deducible,rce_limite_unico,emitido_producto,emitido_cotizacion,source_file
0,2024-10-29T22:22:50.773Z,e515ea0cbd2c6235f9c1bcca3f1182b2,1965-01-01,59,Estudiante,CC,Femenino,00606066,AUDI,CAMIONETA PASAJ.,...,2024-10-29T22:23:13.717191919Z,12428859.6,Todo_riesgo,0 a 1500,SUPERIOR,SUPERIOR,true,Aseguradora9_Todo Riesgo Alto,false,2024-10
1,2024-10-29T22:22:50.773Z,e515ea0cbd2c6235f9c1bcca3f1182b2,1965-01-01,59,Estudiante,CC,Femenino,00606066,AUDI,CAMIONETA PASAJ.,...,2024-10-29T22:23:13.717228755Z,20378380.5,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,Aseguradora9_Todo Riesgo Alto,false,2024-10
2,2024-10-29T22:22:50.773Z,e515ea0cbd2c6235f9c1bcca3f1182b2,1965-01-01,59,Estudiante,CC,Femenino,00606066,AUDI,CAMIONETA PASAJ.,...,2024-10-29T22:23:13.717217028Z,21255093.900000002,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,Aseguradora9_Todo Riesgo Alto,false,2024-10
3,2024-10-29T22:22:50.773Z,e515ea0cbd2c6235f9c1bcca3f1182b2,1965-01-01,59,Estudiante,CC,Femenino,00606066,AUDI,CAMIONETA PASAJ.,...,2024-10-29T22:23:13.717251661Z,20576578.5,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,Aseguradora9_Todo Riesgo Alto,false,2024-10
4,2024-10-16T13:09:37.634Z,eba50136d23a42cf47f7701da546e68d,1995-01-04,29,Empleado,CC,Femenino,01621016,CHEVROLET,PICKUP DOBLE CAB,...,2024-10-16T13:09:51.354573827Z,5265299.7,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,NaN,false,2024-10

In [6]:
df_all.tail()

,fecha_registro,comparison_id,fecha_nacimiento,edad,ocupacion,tipo_identificacion,genero,fasecolda_id,marca,clase,...,cotizacion_fecha,valor_prima,tipo_cobertura,rce,perdida_total_cobertura,perdida_parcial_deducible,rce_limite_unico,emitido_producto,emitido_cotizacion,source_file
2087576,2025-01-28T01:07:51.221Z,b0683e81467db96195277834254937db,1959-06-21,65,Estudiante,CC,Masculino,01601146,CHEVROLET,AUTOMOVIL,...,2025-01-28T01:09:11.646517577Z,1802602.4000000001,Todo_riesgo,0 a 1500,IGUAL,SUPERIOR,true,NaN,false,2025-1
2087577,2025-01-28T01:07:51.221Z,b0683e81467db96195277834254937db,1959-06-21,65,Estudiante,CC,Masculino,01601146,CHEVROLET,AUTOMOVIL,...,2025-01-28T01:09:11.646554207Z,1811198.4000000001,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,NaN,false,2025-1
2087578,2025-01-28T01:07:51.221Z,b0683e81467db96195277834254937db,1959-06-21,65,Estudiante,CC,Masculino,01601146,CHEVROLET,AUTOMOVIL,...,2025-01-28T01:09:11.646546724Z,753728,Cobertura_parcial,0 a 1500,IGUAL,NO CUBRE,true,NaN,false,2025-1
2087579,2025-01-28T01:07:51.221Z,b0683e81467db96195277834254937db,1959-06-21,65,Estudiante,CC,Masculino,01601146,CHEVROLET,AUTOMOVIL,...,2025-01-28T01:09:11.646470584Z,1424872,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,NaN,false,2025-1
2087580,2025-01-28T01:07:51.221Z,b0683e81467db96195277834254937db,1959-06-21,65,Estudiante,CC,Masculino,01601146,CHEVROLET,AUTOMOVIL,...,2025-01-28T01:09:11.646539679Z,1176101.6,Todo_riesgo,>1500,IGUAL,SUPERIOR,true,NaN,false,2025-1

In [9]:
# Guardar el archivo consolidado en formato csv
df_all.to_csv(csv_file, index=False, sep=";", encoding="utf-8-sig")
print(f"âœ… Guardado en formato CSV: {csv_file}")

âœ… Guardado en formato CSV: C:/Allianz/prueba_allianz/data/processed\allianz_consolidado.csv